apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base
  - namespace.yaml
  - dragonfly.yaml
patches:
  - path: replicas.yaml
  - target:
      kind: Ingress
      name: course-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: course-app.dev.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: course-app.dev.local
